# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7-fpm

pipelines:
  build:
    - step:
        name: Manual Deploy
        trigger: manual
        script:
          # Installing first the libraries necessary to configure and install gd
          - apt-get update && apt-get install -qy unzip git curl libmcrypt-dev mysql-client libfreetype6-dev libjpeg62-turbo-dev libpng-dev
          # Now we can configure and install the extension
          - yes | pecl install mcrypt-1.0.1
          - docker-php-ext-install pdo_mysql
          - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
          - docker-php-ext-install -j$(nproc) gd
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          # 启动服务验证
          - cat .hosts >> /etc/hosts
          - ln -f -s .env.pipelines .env
          - php artisan migrate
          - php artisan serve &
          - sleep 5
          - ./vendor/bin/phpunit
          - curl -vk http://localhost:8000

        services:
          - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'

